import { build } from 'esbuild';
import { mkdir, copyFile, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
const root = fileURLToPath(new URL('.', import.meta.url));
const dev = process.argv.includes('--dev');
const output = join(root, 'dist', dev ? 'development' : 'production');
await mkdir(output, { recursive: true });
await build({ entryPoints: [join(root, 'src/background.ts')], bundle: true, format: 'iife', target: 'chrome120', outfile: join(output, 'background.js') });
for (const file of ['content.js', 'popup.html', 'popup.css', 'popup.js', 'options.html', 'options.js']) await copyFile(join(root, file), join(output, file));
await mkdir(join(output, 'fonts'), { recursive: true });
for (const weight of [400, 500, 600]) await copyFile(join(root, '../../node_modules/@fontsource/inter/files', `inter-latin-${weight}-normal.woff2`), join(output, 'fonts', `inter-${weight}.woff2`));
await copyFile(join(root, '../web/public/duckler-logo.svg'), join(output, 'duckler-logo.svg'));
await mkdir(join(output, 'icons'), { recursive: true });
for (const size of [16, 32, 48, 128]) await copyFile(join(root, 'icons', `duck-${size}.png`), join(output, 'icons', `duck-${size}.png`));
const manifest = JSON.parse(await readFile(join(root, 'manifest.json'), 'utf8'));
manifest.externally_connectable = { matches: dev ? ['http://localhost/*', 'http://127.0.0.1/*'] : ['https://duckler.pages.dev/*'] };
await writeFile(join(output, 'manifest.json'), JSON.stringify(manifest, null, 2));
console.log(`Load unpacked: ${output}`);
