import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const baseURL = process.env.DUCKLER_PREVIEW_URL || 'http://localhost:5176';
const output = new URL('../.tmp/ui-checks/', import.meta.url);
const sharedModuleURL = '/@fs/' + fileURLToPath(new URL('../packages/shared/src/index.ts', import.meta.url)).replaceAll('\\', '/');
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(baseURL);
  await page.getByRole('button', { name: 'Collections', exact: true }).waitFor();
  await page.evaluate(async sharedModule => {
    const { cardDb } = await import('/src/lib/cardDb.ts');
    const { createCardFromInput, createCollectionFromInput } = await import(sharedModule);
    const cards = [createCardFromInput({ type: 'bookmark', title: 'Spec checklist', note: 'Track the milestone and accepted behavior.', sourceUrl: 'https://example.com/spec' }), createCardFromInput({ type: 'text', title: 'Design note', note: 'Keep the library local and searchable.' })];
    await cardDb.cards.bulkPut(cards);
    await cardDb.collections.put(createCollectionFromInput({ name: 'Inbox', cardIds: cards.map(card => card.id) }));
  }, sharedModuleURL);
  await page.reload();
  await page.getByRole('button', { name: 'All notes', exact: true }).click();
  await page.getByRole('article', { name: 'Open Spec checklist' }).waitFor();
  const card = page.getByRole('article', { name: 'Open Spec checklist' });
  const actions = page.getByRole('group', { name: 'Actions for Spec checklist' });
  await page.mouse.move(0, 0);
  assert.equal(await actions.evaluate(el => getComputedStyle(el).opacity), '0');
  await card.hover();
  const edit = actions.getByRole('button', { name: 'Edit Spec checklist' });
  await edit.waitFor({ state: 'visible' });
  await expect.poll(() => actions.evaluate(el => getComputedStyle(el).opacity)).toBe('1');
  const cardBox = await card.boundingBox(), actionBox = await actions.boundingBox();
  assert.ok(actionBox.y + actionBox.height <= cardBox.y, 'Controls sit above the card');
  assert.equal(await edit.evaluate(el => getComputedStyle(el).backgroundColor), 'rgba(0, 0, 0, 0)');
  await actions.getByRole('button', { name: 'Move Spec checklist to collection' }).click();
  await actions.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('checkbox', { name: 'Select Spec checklist' }).check();
  assert.equal(await page.getByRole('group', { name: 'Selected card actions' }).count(), 0);
  const secondCard = page.getByRole('article', { name: 'Open Design note' });
  await secondCard.hover();
  await page.getByRole('checkbox', { name: 'Select Design note' }).check();
  const bulk = page.getByRole('group', { name: 'Selected card actions' });
  await bulk.waitFor();
  assert.equal(await bulk.evaluate(el => getComputedStyle(el).position), 'static');
  await page.getByRole('button', { name: 'Clear selection' }).click();
  await page.getByRole('button', { name: 'Add card' }).hover();
  await page.getByRole('button', { name: 'Link', exact: true }).waitFor();
  await card.hover();
  await edit.click();
  const editor = page.getByRole('dialog', { name: 'Card details' });
  await editor.getByRole('textbox', { name: 'Note' }).waitFor();
  await page.screenshot({ path: fileURLToPath(new URL('card-editor.png', output)), fullPage: true });
  for (const width of [320, 390]) {
    await page.setViewportSize({ width, height: 800 });
    const save = await editor.getByRole('button', { name: 'Save', exact: true }).boundingBox();
    assert.ok(save && save.x >= 0 && save.x + save.width <= width && save.y + save.height <= 800, 'Editor Save stays visible on phones');
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await editor.getByRole('button', { name: 'Close details' }).click();
  const badge = card.locator('..').getByRole('button', { name: 'Collection Inbox', exact: true });
  await badge.click();
  const picker = page.getByRole('dialog', { name: 'Collections for this card' });
  await picker.getByRole('checkbox', { name: 'Inbox', exact: true }).uncheck();
  await page.getByRole('button', { name: 'Undo', exact: true }).waitFor();
  await page.keyboard.press('Escape');
  await expect(picker).toHaveCount(0);
  await expect(badge).toHaveCount(0);
  await expect(card).toBeVisible();
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(badge).toBeVisible();
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toHaveCount(0);
  await page.reload();
  await page.getByRole('button', { name: 'All notes', exact: true }).click();
  await expect(badge).toBeVisible();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  assert.ok((await page.locator('link[data-browser-icon]').getAttribute('href')).endsWith('duck-tab-light.png'));
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.waitForFunction(() => document.querySelector('link[data-browser-icon]').href.endsWith('duck-tab-dark.png'));
  await page.emulateMedia({ colorScheme: 'light' });
  await page.waitForFunction(() => document.querySelector('link[data-browser-icon]').href.endsWith('duck-tab-light.png'));
  await page.evaluate(() => document.fonts.ready);
  const grid = await page.locator('.library-grid').boundingBox();
  assert.ok(Math.abs(grid.x + grid.width / 2 - 720) < 3, 'Library cards should be centered');
  assert.equal(await page.locator('.card-tile').first().evaluate(el => getComputedStyle(el).borderRadius), '2px'); // PS2 schematic: near-square corners by default
  const cards = await page.locator('.library-card').evaluateAll(elements => elements.map(el => ({ x: el.getBoundingClientRect().x, y: el.getBoundingClientRect().y, width: el.getBoundingClientRect().width })));
  assert.equal(cards[0].y, cards[1].y, 'Two starter cards should sit side by side');
  assert.ok(Math.abs((cards[0].x + cards[1].x + cards[1].width) / 2 - 720) < 3);
  assert.equal(await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button').count(), 4);
  await page.waitForTimeout(250);
  await page.screenshot({ path: fileURLToPath(new URL('desktop.png', output)), fullPage: true, animations: 'disabled' });
  const accountMenu = page.getByRole('dialog', { name: 'Account menu' });
  await page.getByRole('button', { name: 'Account menu' }).hover();
  await accountMenu.waitFor();
  assert.equal(await accountMenu.evaluate(el => getComputedStyle(el).backdropFilter), 'none', 'PS2 schematic: no blur on popovers');
  await page.screenshot({ path: fileURLToPath(new URL('profile.png', output)), animations: 'disabled' });
  assert.equal(await page.getByRole('textbox', { name: 'Profile name' }).count(), 0);
  await page.mouse.move(100, 500);
  await accountMenu.waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Open settings' }).click();
  await page.getByRole('dialog', { name: 'Settings' }).waitFor();
  await page.screenshot({ path: fileURLToPath(new URL('settings.png', output)), fullPage: true, animations: 'disabled' });
  await page.keyboard.press('Escape');
  await page.getByRole('dialog', { name: 'Settings' }).waitFor({ state: 'hidden' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'All items' }).focus();
  await page.mouse.move(380, 100);
  await page.screenshot({ path: fileURLToPath(new URL('mobile.png', output)), fullPage: true, animations: 'disabled' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'No horizontal overflow on mobile');
  const dock = await page.getByRole('navigation', { name: 'Main navigation' }).boundingBox();
  const add = await page.getByRole('button', { name: 'Add card', exact: true }).boundingBox();
  assert.ok(dock.y + dock.height < add.y || dock.x + dock.width < add.x, 'Navigation and add button should not overlap');
  for (const [width, height] of [[320, 568], [360, 640], [414, 896], [768, 1024], [1024, 600], [667, 375]]) {
    await page.setViewportSize({ width, height });
    await page.getByRole('button', { name: 'Duckler home' }).click();
    const launcher = await page.locator('.home-launcher').boundingBox();
    assert.ok(Math.abs(launcher.x + launcher.width / 2 - width / 2) < 2, `Home stays horizontally centered at ${width}`);
    assert.ok(Math.abs(launcher.y + launcher.height / 2 - height / 2) < 25, `Home stays vertically centered at ${width}`);
    assert.ok(launcher.width <= 300, 'Home shortcuts stay close together');
    assert.equal(await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button').count(), 4, 'Home keeps all dock shortcuts');
    assert.equal(await page.getByLabel('Search refs').count(), 1, 'Populated Home keeps its search');
    assert.equal(await page.getByRole('navigation', { name: 'Filter by media type' }).count(), 0);
    await page.screenshot({ path: fileURLToPath(new URL(`home-${width}.png`, output)), animations: 'disabled' });
    await page.getByRole('button', { name: 'All notes', exact: true }).click();
    assert.equal(await page.getByRole('button', { name: 'Go back' }).count(), 1);
    const firstCard = await page.locator('.library-card').first().boundingBox();
    if (width <= 560) assert.ok(firstCard.y < 300, `Small screens should show content without a huge header: ${firstCard.y}`);
    const plus = await page.getByRole('button', { name: 'Add card', exact: true }).boundingBox();
    const navigation = await page.getByRole('navigation', { name: 'Main navigation' }).boundingBox();
    assert.ok(plus.width >= (width <= 560 ? 64 : 76), `Larger add control at ${width}`);
    assert.ok(navigation.x + navigation.width <= plus.x || navigation.y + navigation.height <= plus.y, `Dock and larger add button remain separate at ${width}`);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `No overflow at ${width}×${height}`);
    await page.locator('.library-options > summary').click();
    const menu = await page.locator('.library-options-popover').boundingBox();
    assert.ok(menu.x >= 0 && menu.x + menu.width <= width + 1, `Options menu stays on screen at ${width}: ${JSON.stringify(menu)}`);
    assert.ok(menu.y >= 0 && menu.y + menu.height <= height + 1, `Options stays vertically on screen at ${width}`);
    await page.locator('.library-options > summary').click();
    await page.getByRole('button', { name: 'Open settings' }).click();
    assert.equal(await page.getByRole('dialog', { name: 'Settings' }).evaluate(el => el.scrollWidth > el.clientWidth), false, `Settings fits at ${width}`);
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'Account menu' }).hover();
    await page.getByRole('dialog', { name: 'Account menu' }).waitFor();
    const preview = await page.getByRole('dialog', { name: 'Account menu' }).boundingBox();
    assert.ok(preview.x >= 0 && preview.x + preview.width <= width + 1, `Account menu stays on screen at ${width}: ${JSON.stringify(preview)}`);
    assert.ok(preview.y >= 0 && preview.y + preview.height <= height + 1, `Account menu fits vertically at ${width}`);
    await page.mouse.move(width - 1, 0);
    await page.getByRole('button', { name: 'All items' }).focus();
    await page.screenshot({ path: fileURLToPath(new URL(`viewport-${width}.png`, output)), fullPage: true, animations: 'disabled' });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.getByRole('button', { name: 'All items' }).evaluate(el => getComputedStyle(el).backgroundColor), 'rgba(0, 0, 0, 0)');
  await page.getByRole('button', { name: 'Add card', exact: true }).click();
  await page.getByRole('button', { name: 'Note', exact: true }).click();
  const composer = page.getByRole('dialog', { name: 'Add card' });
  await composer.getByRole('textbox', { name: 'Title', exact: true }).fill('Animated note check');
  await composer.getByRole('textbox', { name: 'Note', exact: true }).fill('A saved note from the isolated browser check.');
  await composer.getByRole('button', { name: 'Collections', exact: true }).click();
  assert.equal(await page.locator('.composer-collections').evaluate(el => getComputedStyle(el).animationName), 'composer-slide');
  for (const width of [320, 360, 390]) {
    await page.setViewportSize({ width, height: 640 });
    const save = await composer.getByRole('button', { name: 'Save', exact: true }).boundingBox();
    assert.ok(save.x >= 0 && save.x + save.width <= width, `Save remains visible at ${width}`);
    assert.equal(await page.locator('.card-composer').evaluate(el => el.scrollWidth > el.clientWidth), false, `Editor fits at ${width}`);
    assert.ok(save.height >= 44, 'Save has a usable touch target');
    assert.equal(await page.evaluate(() => document.elementFromPoint(1, 1)?.closest('.composer-backdrop') !== null), true, 'The editor covers the whole viewport');
    await page.screenshot({ path: fileURLToPath(new URL(`composer-${width}.png`, output)), fullPage: true, animations: 'disabled' });
  }
  await page.screenshot({ path: fileURLToPath(new URL('composer.png', output)), fullPage: true, animations: 'disabled' });
  await composer.getByRole('button', { name: 'Save', exact: true }).click();
  await composer.waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Close details' }).click();
  await page.getByRole('article', { name: 'Open Animated note check' }).waitFor();
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert.equal(await page.locator('.library-card.is-new').evaluate(el => getComputedStyle(el).animationName), 'none');
  await page.getByRole('button', { name: 'Collections', exact: true }).click();
  assert.equal(await page.getByRole('navigation', { name: 'Filter by media type' }).count(), 0);
  const emptyContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const emptyPage = await emptyContext.newPage();
  await emptyPage.goto(baseURL);
  await emptyPage.locator('.home-launcher').waitFor();
  assert.equal(await emptyPage.getByRole('heading', { name: 'refs' }).count(), 0);
  assert.equal(await emptyPage.getByLabel('Search refs').count(), 1, 'Empty Home keeps its search too');
  await emptyPage.getByRole('button', { name: 'Collections', exact: true }).hover();
  await emptyPage.waitForTimeout(350);
  await emptyPage.screenshot({ path: fileURLToPath(new URL('empty-desktop.png', output)), fullPage: true, animations: 'disabled' });
  await emptyPage.setViewportSize({ width: 390, height: 844 });
  await emptyPage.screenshot({ path: fileURLToPath(new URL('empty-mobile.png', output)), fullPage: true, animations: 'disabled' });
  assert.equal(await emptyPage.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.setViewportSize({ width: 1440, height: 800 });
  await page.evaluate(async sharedModule => {
    const { cardDb } = await import('/src/lib/cardDb.ts');
    const { createCardFromInput } = await import(sharedModule);
    await cardDb.cards.bulkPut(Array.from({ length: 12 }, (_, index) => createCardFromInput({ type: 'text', title: `Scroll check ${index}`, note: 'A longer reference note to exercise the floating search and small clearance motion. '.repeat(5) })));
  }, sharedModuleURL);
  await page.reload();
  await page.getByRole('button', { name: 'All notes', exact: true }).click();
  await page.locator('.library-card').nth(10).waitFor();
  await page.evaluate(() => {
    const card = document.querySelectorAll('.library-card')[2];
    window.scrollTo(0, card.getBoundingClientRect().top + scrollY - 80);
  });
  await page.waitForFunction(() => document.querySelector('.refs-search')?.dataset.docked === 'true');
  const searchBounds = await page.locator('.refs-search').boundingBox();
  assert.ok(searchBounds.y >= 21 && searchBounds.y <= 23, 'Search stays pinned beside the top controls while scrolling');
  // Cards no longer shift away from the docked search (measuring every card on scroll cost frames).
  const clearance = await page.locator('.library-card').evaluateAll(cards => cards.map(card => Math.abs(parseFloat(card.style.getPropertyValue('--search-clearance'))) || 0));
  assert.ok(clearance.every(value => value === 0), 'Cards stay still while scrolling under the search');
  await page.screenshot({ path: fileURLToPath(new URL('scroll-search.png', output)), animations: 'disabled' });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.waitForFunction(() => document.querySelector('.refs-search')?.dataset.docked === 'false');
  assert.deepEqual(errors, []);
  console.log('Desktop/mobile layout, dark default, account menu hover, settings and keyboard dismissal passed.');
} finally { await browser.close(); }


